name: Zip Action for Widget
on: [push]
jobs:
  Zip-Widget:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Zipping job automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - run: zip today.widget.zip today.jsx today.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating widget zipfile


